#%RAML 1.0 NamedExample
{
"country":"Martinique",
"email":"at@justofaucibuslectus.edu",
"first_name":"Cole",
"id":8,
"last_name":"Aiko",
"phone":"(230) 826-1281",
"breed":[
   "dalmatian",
    "eskimo"],
      "pet":"dog"
   }