#%RAML 1.0 NamedExample
[
   {
      "breed":[
         "dalmatian",
         "eskimo"
      ],
      "id":0,
      "pet":"dog"
   },
   {
      "breed":[
         "entlebucher"
      ],
      "id":1,
      "pet":"dog"
   },
   {
      "breed":[
         "african",
         "pug",
         "akita"
      ],
      "id":2,
      "pet":"dog"
   },
   {
      "breed":[
         "malinois",
         "mastiff-bull"
      ],
      "id":3,
      "pet":"dog"
   },
   {
      "breed":[
         "Maine Coon",
         "Ragdoll"
      ],
      "id":4,
      "pet":"cat"
   },
   {
      "breed":[
         "Persian",
         "Siamese",
         "Tonkinese"
      ],
      "id":5,
      "pet":"cat"
   },
   {
      "breed":[
         "Bengal"
      ],
      "id":6,
      "pet":"cat"
   },
   {
      "breed":[
         "Burmese Cat",
         "Bombay Cat",
         "Bengal Cat"
      ],
      "id":7,
      "pet":"cat"
   },
   {
      "breed":[
         "Korat"
      ],
      "id":8,
      "pet":"cat"
   },
   {
      "breed":[
         "Japanese Bobtail",
         "Manx"
      ],
      "id":9,
      "pet":"cat"
   }
]